dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: T+95vPkXeOqLjfPGmTzOrVKR56hjh1WaWl4+dPHj9/j7fQ/UlHkmyDUlvzYQi5zleSMftmPgg7Kc1s+KcBnMWiX5ckfYQyQhJnWYaBVqiCz27OnGSkyK9EphCopr8Ao58LQPqBa7r+2iRVrQVVpTHCNnqdvdxzPLmLxkx2Gqu7nSbQ9OugTkMC4+LcSyhPWJU9SSKmlSXU1G2HPJpYcuiB+5beV3fiA0XLfrImf8bXiuXQCyKmpp/0oGIf9z82lGD54U5eSwBShb4THJJGh3s/oxZ3OpZQQ3q9lhIm+Kgfwd3m+VojQ9LPgdCRLPgnuycj/QHaggkcavkD4Zm/jLhWFwi221Y8Ta1g+Ex8QwNHGqjOrfAMpuxDOmpC8DNzD2MqIwRkfyBXXnJU5wgszx0NtLeZLhwJvKLSB23aa4qwtkwZqgAJHe4jXrHXlRxPFj5LGPdeAqcFVRJmUScZBBVyKjzYR/6uWmP76wqwtrcbZkdkXlzj3FhYcd8iBCCJynhToeNxr5CtVlC8250L1Y+U4XlTjvL8geiy/8EJR6MOs7HH1fEKEMj7JuWhyvW9mEoDxBMiQgGs//AMaOBaWCj5uz4Ad1kqwzR7x4FsSx1dKT9mj0HKcoVXWtfzZXVq3a33E0SzpeitUwuKw4YLXRQEt60KyK8VvTOBVCa+QMKr8=
  file: Gerbers/PRO-101_gerbers.zip
  on:
    repo: w4xzr/PRO-101
  skip_cleanup: 'true'
